<Window x:Class="nLogViewer.Views.ErrorWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:local="clr-namespace:nLogViewer.Views"
        mc:Ignorable="d"
        Title="Ошибка приложения" 
        SizeToContent="WidthAndHeight"
        Icon="../Infrastructure/Resources/Images/Medium/bug.png"
        ResizeMode="NoResize"
        WindowStartupLocation="CenterScreen">
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="40"/>
            <RowDefinition Height="40"/>
            <RowDefinition Height="Auto"/>
        </Grid.RowDefinitions>
        <StackPanel Orientation="Horizontal" Margin="10,0">
            <Image Source="../Infrastructure/Resources/Images/Large/bug-report.png"></Image>
            <TextBlock Text="В результате выполнения программы было сгенерировано исключение:" 
                       FontSize="14" 
                       Margin="10"/>
        </StackPanel>
        <TextBlock Grid.Row="1" Name="ExceptionDescription" 
                   Text="Текстовое описание ошибки" 
                   TextAlignment="Center"
                   FontSize="14" 
                   TextWrapping="Wrap"
                   Margin="10"/>
        <WrapPanel Grid.Row="2" HorizontalAlignment="Right">
            <Button Content="Ok" IsCancel="True" 
                    MinWidth="100" MinHeight="30" Margin="10"/>
        </WrapPanel>
    </Grid>
</Window>
